# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

r:
  - 3.5
  # - bioc-release
  # - bioc-devel

os:
  # - linux
  - osx

matrix:
  exclude:
  - os: osx
    r: bioc-devel

# blocklist
# branches:
#   except:
#  - develop

# safelist
# branches:
#   only:
#   - master

# External dependencies
# dependency for clusterProfiler > enrichplot > udunits2
addons:
  apt:
    update: true
    packages:
      - libudunits2-dev

env:
  global:
    - LINTR_COMMENT_BOT=true

# r_build_args: "--no-build-vignettes"
# r_check_args: "--no-vignettes"

# Set true before submission to Bioconductor
warnings_are_errors: false

# Temporarily enable when caching Bioconductor packages
# script: true

r_packages:
  - covr
  - hexbin
bioc_packages:
  - BiocCheck
  - GenomeInfoDbData
  - S4Vectors
  - DelayedArray
  - EnsDb.Hsapiens.v75
  - DEGreport
  # clusterProfiler dependencies
  - ALL
  - DO.db
  - GO.db
  - enrichplot
  - org.Hs.eg.db
  - org.Mm.eg.db
r_github_packages:
  - jimhester/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck .
  - chmod +x travis_render.sh
  - ./travis_render.sh

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: always
