# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

matrix:
  include:
  - os: linux
    r: bioc-release
  - os: osx
    r: bioc-release
  fast_finish: true

branches:
  only:
  - master

env:
  global:
    - LINTR_COMMENT_BOT=true

r_packages:
  - covr
  - hexbin
bioc_packages:
  - BiocCheck
  - GenomeInfoDbData
  - S4Vectors
  - DelayedArray
  - EnsDb.Hsapiens.v75
r_github_packages:
  - steinbaugh/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck .
  # Render R Markdown templates
  # https://github.com/bcbio/bcbio_rnaseq_output_example
  # - chmod +x travis_render.sh
  # - ./travis_render.sh

notifications:
  email:
    on_success: change
    on_failure: change
