# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

# Temporarily enable when caching package library.
# script: true

language: r
cache: packages
sudo: false
bioc_required: true

matrix:
  include:
  - os: osx
    r: bioc-release
    fortran: false
    latex: false
    warnings_are_errors: false
  - os: linux
    r: bioc-release
    warnings_are_errors: true
  - os: linux
    r: bioc-devel
    latex: false
    warnings_are_errors: true
  fast_finish: true

env:
  global:
    - LINTR_COMMENT_BOT=true

r_packages:
  - covr
  - hexbin
bioc_packages:
  - BiocCheck
  - GenomeInfoDbData
  - S4Vectors
  - DelayedArray
  - EnsDb.Hsapiens.v75
r_github_packages:
  - jimhester/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck .
  # Render R Markdown templates
  # https://github.com/bcbio/bcbio_rnaseq_output_example
  # - chmod +x travis_render.sh
  # - ./travis_render.sh

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: always
