language: r
cache: packages

script: true

matrix:
  include:
    - os: linux
      r: bioc-release
    - os: linux
      r: bioc-devel
    - os: osx
      r: bioc-release
  allow_failures:
    - os: osx
    - r: bioc-devel
  fast_finish: true

branches:
  only:
    - master

env:
  global:
    - LINTR_COMMENT_BOT=true

r_packages:
  - covr
  - hexbin
  - rmarkdown
  - tidyverse
bioc_packages:
  - BiocCheck
  - GenomeInfoDbData
  - S4Vectors
  - DelayedArray
  - EnsDb.Hsapiens.v75
r_github_packages:
  - acidgenomics/lintr

after_success:
  - R CMD BiocCheck .
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  # - chmod +x travis_render.sh
  # - ./travis_render.sh

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
