language: general

services:
  - docker

branches:
  only:
    - master

install:
  - curl -sSL https://raw.githubusercontent.com/acidgenomics/Rcheck/master/install | bash

before_script:
    # Avoid BiocCheck > checkCodingPractice > checkLogicalUseFiles error.
  - touch inst/rmarkdown/templates/{differential-expression,functional-analysis,quality-control}/skeleton/_{footer,header,links}.Rmd

jobs:
  include:
    - stage: test
      name: "bioc-3.9"
      script: image="r-bcbio" tag="bioc-3.9" ./.Rcheck/docker
    - stage: test
      name: "bioc-3.8"
      script: image="r-bcbio" tag="bioc-3.8" ./.Rcheck/docker
    - stage: test
      name: "bioc-devel"
      script: image="r-bcbio" tag="bioc-devel" ./.Rcheck/docker

matrix:
  allow_failures:
    - name: "bioc-devel"
  fast_finish: true

after_failure:
  - ./.Rcheck/docker-failure

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
