language: r
cache: packages
sudo: false
dist: trusty
warnings_are_errors: false
r:
  - bioc-release
  - bioc-devel
r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - lpantano/DEGreport
after_success:
  - Rscript -e 'covr::codecov()'
  - pwd
  - cd ..
  - git clone https://github.com/bcbio/bcbio_rnaseq_output_example.git
  - mkdir template
  - cd template
  - cp ../bcbio_rnaseq_output_example/setup.R .
  - cp ../bcbioRnaseq/inst/rmarkdown/templates/quality_control/skeleton/skeleton.Rmd qc.Rmd
  - Rscript -e 'devtools::install_local("../bcbioRnaseq")'
  - Rscript -e 'library(methods);bcbioRnaseq::downloads();rmarkdown::render("qc.Rmd")'
  - cp ../bcbioRnaseq/inst/rmarkdown/templates/differential_expression/skeleton/skeleton.Rmd de.Rmd
  - Rscript -e 'library(methods);rmarkdown::render("de.Rmd")'
  - ls
  - cd ../bcbio_rnaseq_output_example
  - cp ../bcbioRnaseq/.push.sh push.sh
  - chmod +x push.sh
  - ./push.sh
