language: general

services:
  - docker

branches:
  only:
    - master

before_script:
  - chmod +x travis-docker.sh
  # Avoid BiocCheck > checkCodingPractice > checkLogicalUseFiles error.
  - touch inst/rmarkdown/templates/quality-control/skeleton/_{footer,header,links}.Rmd

jobs:
  include:
    - stage: test
      name: "Docker: Bioconductor 3.9"
      script: tag="bioc-3.9" ./travis-docker.sh
    - stage: test
      name: "Docker: Bioconductor 3.8"
      script: tag="bioc-3.8" ./travis-docker.sh
    - stage: test
      name: "Docker: Bioconductor 3.7"
      script: tag="bioc-3.7" ./travis-docker.sh

matrix:
  fast_finish: true

after_failure:
  - env | sort
  - df -h
  - docker images

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
