# R for travis
# https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: false

# Temporarily enable when caching Bioconductor packages
# script: true

r:
  - bioc-release
  - bioc-devel
r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
  - pwd
  - cd ..
  - git clone https://github.com/bcbio/bcbio_rnaseq_output_example.git
  - cd bcbio_rnaseq_output_example
  - Rscript -e 'devtools::install_local("../bcbioRNASeq")'
  - Rscript -e 'devtools::install_github("lpantano/DEGreport")'
  - Rscript -e 'install.packages("DT")'
  - Rscript -e 'install.packages("tidyverse")'
  - Rscript -e 'install.packages("formatR")'
  - Rscript -e 'testthat::test_file("test_reports.R")'
  - cd report
  - mv de.html de-${TRAVIS_BRANCH}.html
  - mv qc.html qc-${TRAVIS_BRANCH}.html
  - mv fa.html fa-${TRAVIS_BRANCH}.html
  - cd ..
  - cp ../bcbioRNASeq/.push.sh push.sh
  - chmod +x push.sh
  - ./push.sh
