# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

matrix:
  include:
    - os: linux
      r: bioc-release
    - os: osx
      r: bioc-release
  fast_finish: true

branches:
  only:
    - master

env:
  global:
    - LINTR_COMMENT_BOT=true

# Skipping vignettes, which can cause the build to time out.
r_build_args: "--no-build-vignettes --no-manual"
r_check_args: "--no-build-vignettes --no-manual --timings"

r_packages:
  - covr
  - hexbin
bioc_packages:
  - BiocCheck
  - GenomeInfoDbData
  - S4Vectors
  - DelayedArray
  - EnsDb.Hsapiens.v75
r_github_packages:
  - steinbaugh/lintr

after_success:
  - R CMD BiocCheck .
  # Only check lints and coverage against linux bioc-release.
  - test $TRAVIS_OS_NAME = 'linux' && $TRAVIS_R_VERSION_STRING = 'bioc-release' && Rscript -e 'lintr::lint_package()'
  - test $TRAVIS_OS_NAME = 'linux' && $TRAVIS_R_VERSION_STRING = 'bioc-release' && Rscript -e 'covr::codecov()'
  # Render R Markdown templates
  # https://github.com/bcbio/bcbio_rnaseq_output_example
  # - chmod +x travis_render.sh
  # - ./travis_render.sh

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
