# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
os: osx
bioc_required: true

r:
  - 3.4
  - 3.5
  - release

branches:
  only:
- master

env:
  global:
    - BIOC_USE_DEVEL="FALSE"

r_packages:
  - covr
  - hexbin
bioc_packages:
  - BiocCheck
  - GenomeInfoDbData
  - S4Vectors
  - DelayedArray
  - EnsDb.Hsapiens.v75
  - DEGreport
  # clusterProfiler dependencies
  - ALL
  - DO.db
  - GO.db
  - enrichplot
  - org.Hs.eg.db
  - org.Mm.eg.db
r_github_packages:
  - acidgenomics/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck .
  - chmod +x travis_render.sh
  - ./travis_render.sh

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: always
