init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

platform: x64

branches:
  only:
    - master

environment:
  global:
    BIOC_USE_DEVEL: "FALSE"
    GCC_PATH: mingw_64
    R_ARCH: x64
    USE_RTOOLS: true
  matrix:
    - configuration: 3.4
      R_VERSION: 3.4.4
    - configuration: 3.5
      R_VERSION: 3.5.3
    - configuration: release
      R_VERSION: release

matrix:
  allow_failures:
    - configuration: devel
  fast_finish: true

build_script:
  - travis-tool.sh install_bioc GenomeInfoDbData
  - travis-tool.sh install_bioc DelayedArray
  - travis-tool.sh install_bioc ensembldb
  - travis-tool.sh install_bioc DEGreport
  - travis-tool.sh install_bioc EnsDb.Hsapiens.v75
  # clusterProfiler dependencies
  - travis-tool.sh install_bioc ALL
  - travis-tool.sh install_bioc DO.db
  - travis-tool.sh install_bioc GO.db
  - travis-tool.sh install_bioc enrichplot
  - travis-tool.sh install_bioc org.Hs.eg.db
  - travis-tool.sh install_bioc org.Mm.eg.db
  - travis-tool.sh install_r data.table
  - travis-tool.sh install_bioc_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs
  - path: '*.Rcheck\**\*.out'
    name: Logs
  - path: '*.Rcheck\**\*.fail'
    name: Logs
  - path: '*.Rcheck\**\*.Rout'
    name: Logs
  - path: '\*_*.tar.gz'
    name: Bits
  - path: '\*_*.zip'
    name: Bits
  - path: all-Rout.zip
    name: AllRout

notifications:
  - provider: Email
    to:
      - mike@steinbaugh.com
    on_build_status_changed: true
