# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  # - C:\RLibrary

# Adapt as necessary starting from here

environment:
  global:
    _R_CHECK_FORCE_SUGGESTS_: FALSE
    BIOC_USE_DEVEL: TRUE
    R_ARCH: x64
    USE_RTOOLS: TRUE
    # WARNINGS_ARE_ERRORS: 1

build_script:
  - Rscript -e "source('http://bioconductor.org/biocLite.R')"
  - travis-tool.sh install_bioc GenomeInfoDbData
  - travis-tool.sh install_bioc DelayedArray
  - travis-tool.sh install_github jotsetung/ensembldb
  - travis-tool.sh install_github lpantano/DEGreport
  - travis-tool.sh install_bioc EnsDb.Hsapiens.v75
  # clusterProfiler dependencies
  - travis-tool.sh install_bioc ALL
  - travis-tool.sh install_bioc DO.db
  - travis-tool.sh install_bioc GO.db
  - travis-tool.sh install_bioc enrichplot
  - travis-tool.sh install_bioc org.Hs.eg.db
  - travis-tool.sh install_bioc org.Mm.eg.db
  - travis-tool.sh install_r data.table
  - travis-tool.sh install_bioc_deps
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
