# AppVeyor-CI configuration for Bioconductor packages
# https://github.com/krlmlr/r-appveyor

# Download script file from GitHub.
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

platform: x64

# Cache size limit is currently too small for R packages.
# cache:
#   - C:\RLibrary

environment:
  global:
    _R_CHECK_FORCE_SUGGESTS_: false
    # BIOC_USE_DEVEL: true
    R_ARCH: x64
    USE_RTOOLS: true
    # WARNINGS_ARE_ERRORS: 1

# GenomicFeatures > GenomicRanges error
# Error: package or namespace load failed for 'GenomicRanges':
#   (converted from warning) no function found corresponding to methods exports
#   from 'XVector' for: 'concatenateObjects'
# Error : package 'GenomicRanges' could not be loaded
# ERROR: lazy loading failed for package 'GenomicFeatures'

# clusterProfiler dependencies:
# - travis-tool.sh install_bioc ALL
# - travis-tool.sh install_bioc DO.db
# - travis-tool.sh install_bioc GO.db
# - travis-tool.sh install_bioc enrichplot
# - travis-tool.sh install_bioc org.Hs.eg.db
# - travis-tool.sh install_bioc org.Mm.eg.db
# - travis-tool.sh install_r data.table

build_script:
  - travis-tool.sh install_bioc GenomeInfoDbData
  - travis-tool.sh install_bioc DelayedArray
  - travis-tool.sh install_bioc ensembldb
  - travis-tool.sh install_bioc EnsDb.Hsapiens.v75
  - travis-tool.sh install_bioc_deps
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
